apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: three-tier

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
      - name: backend

        image: 610269527042.dkr.ecr.ap-south-1.amazonaws.com/three-tier/backend:26

        imagePullPolicy: Always

        ports:
        - containerPort: 3500

        env:
        - name: MONGO_CONN_STR
          value: mongodb://mongodb:27017/todo?authSource=admin

        - name: USE_DB_AUTH
          value: "true"

        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGO_INITDB_ROOT_USERNAME

        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGO_INITDB_ROOT_PASSWORD

        resources:
          requests:
            cpu: 200m
            memory: 256Mi

          limits:
            cpu: 500m
            memory: 512Mi
