global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'ameyapatil321@gmail.com'
  smtp_auth_username: 'ameyapatil321@gmail.com'
  smtp_auth_password: 'azbo agts urui rrxj'

route:
  receiver: gmail

receivers:
- name: gmail
  email_configs:
  - to: 'ameyapatil321@gmail.com'
    send_resolved: true
